const pricingPackages = {
  landing: {
    type: "basic",
    title: "Standard Package",
    price: "R2,000",
    features: [
      "Single Page Design",
      "Mobile Responsive",
      "Contact Form",
      "Basic SEO Setup",
      "1 Revision Round",
      "Fast Loading Time",
      "Custom Domain Setup",
    ],
  },
  business: {
    type: "standard",
    title: "Business Package",
    price: "R3,500",
    features: [
      "Up to 5 Pages",
      "Mobile Responsive",
      "Contact Form",
      "Standard SEO Setup",
      "Social Media Integration",
      "Basic Business Logic",
      "2 Revision Rounds",
      "1 Month Support",
      "Google Analytics Setup",
    ],
  },
  custom: {
    type: "premium",
    title: "Premium Package",
    price: "R7,000+",
    features: [
      "Full Fledged Fullstack",
      "Custom Design & Logic",
      "Security Implementations",
      "Advanced SEO",
      "Content Management System",
      "Performance Optimization",
      "3 Revision Rounds",
      "3 Months Support",
      "Database Integration",
      "User Authentication",
    ],
  },
  hybrid: {
    type: "hybrid",
    title: "Hybrid Package",
    price: "20% off first month",
    monthlyPrice: "then R850/month",
    popular: true,
    features: [
      "Unlimited Revisions",
      "Free Maintenance",
      "Priority Support",
      "Unlimited Custom Designs",
      "Unlimited Business Logic",
      "Monthly Performance Reports",
      "SEO Optimization",
      "Unlimited Email Accounts",
      "Custom Domain Name",
      "Web Hosting",
    ],
    note: "This is a 12-month partnership agreement that provides ongoing development and support. Perfect for businesses looking for a long-term technology partner rather than a one-time service.",
  },
};
